baseurl = "https://goremote.li/"  # Include trailing slash
title = "goremoteli"
theme = "newsroom"
author = "Irma"
copyright = "Copyright © 2019"
canonifyurls = true
paginate = 10
# Enable syntax highlighting
# comment or delete the following lines 11 ~ 14
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

# ids used below are not valid. Replace with valid ones
[params]
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1
  
  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  twitter = "@_justirma" # twitter handle e.g @weru

